// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYB0hlwAXNwFu3AGi4s4ZUj9Eds9QH8Ek',
    appId: '1:507508833374:web:80b94c4fc70526922908cf',
    messagingSenderId: '507508833374',
    projectId: 'chatapp-59b21',
    authDomain: 'chatapp-59b21.firebaseapp.com',
    storageBucket: 'chatapp-59b21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2wz3loj5wzsoK94bcr8yeAJ0colovUQI',
    appId: '1:507508833374:android:24a3ae1639d527dd2908cf',
    messagingSenderId: '507508833374',
    projectId: 'chatapp-59b21',
    storageBucket: 'chatapp-59b21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy2BZ3F3fblJBkrESsf9eqT3ldmIfWNjI',
    appId: '1:507508833374:ios:721b196d0a7842372908cf',
    messagingSenderId: '507508833374',
    projectId: 'chatapp-59b21',
    storageBucket: 'chatapp-59b21.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
